### ISSUE TITLE
set Stripe api version seems to be ignored

### ISSUE THREAD

**Issue by sfarkas1988** [thephpleague/omnipay-stripe#135]
I'm trying to use the newest api version for stripe with your code base.
I couldn't find a way on how to set the apiVersion within your code. What I did is I called the following method before calling any API method:

`\Stripe\Stripe::setApiVersion("2019-05-16");`
More infos: https://stripe.com/docs/api/versioning

But in the response header i.e of the authorize method, I get this: 

> stripe-version: 2018-09-24

Setting the apiVersion explicitly would be great.

Update:

\Omnipay\Stripe\Message\AbstractRequest::getHeaders is not setting the value as needed in this api doc: https://stripe.com/docs/api/versioning?lang=curl

I even couldn't find a way to set the version.

**Comment by domis86** [comment]
@sfarkas1988 you can resolve this using Guzzle like this:
```
    App\Payment\StripeService:
        arguments:
            $omnipayHttpClient: '@app.payment.omnipay_stripe_http_client'

    app.payment.omnipay_stripe_http_client:
        class: Omnipay\Common\Http\Client
        public: true
        arguments:
            $httpClient: '@app.payment.stripe_guzzle_client'

    app.payment.stripe_guzzle_client:
        class: Http\Adapter\Guzzle6\Client
        public: true
        factory: ['Http\Adapter\Guzzle6\Client', 'createWithConfig']
        arguments:
            $config:
                headers:
                    Stripe-Version: '%stripe_api_version%'
                    User-Agent: 'MyAppHttpClient/%server_hostname% Env/%kernel.environment% PHP/%php_version%'
                http_errors: false
```
^ You should set ```stripe_api_version``` parameter in container (for example parameters.yml or ".env" etc)

Maybe such solution should be mentioned in docs?
